### ISSUE TITLE
Multivariate support of plot.cov

### ISSUE THREAD

**Issue by lorebon** [ntarabelloni/roahd#6] opened 2022-02-08 09:53 UTC
From the example of the roahd documentation:

"# Generating a univariate functional dataset
N = 1e2
P = 1e2
t0 = 0
t1 = 1
time_grid = seq( t0, t1, length.out = P )
Cov = exp_cov_function( time_grid, alpha = 0.3, beta = 0.4 )
D1 = generate_gauss_fdata( N, centerline = sin( 2 * pi * time_grid ), Cov = Cov )
fD1 = fData( time_grid, D1 )
plot( cov_fun( fD1 ), main = 'Covariance function', xlab = 'time', ylab = 'time' )"

I tried to execute the 'plot( cov_fun(mfData), main = 'Covariance function', xlab = 'time', ylab = 'time' )' command, with mfData is a multivariate functional dataset, but I get the following error:

`Error in xy.coords(x, y, xlabel, ylabel, log) : 
  'x' is a list, but does not have components 'x' and 'y'`

I kindly ask again for you assistance, thank you in advance!

**Comment by astamm** [comment] 2022-02-08 13:42
Thanks for reporting this. I will look into it.

**Comment by astamm** [comment] 2022-02-08 14:56
I created a branch `ggplot2-conversion` in which I started to work on this. It still lacks some support and documentation but you should be good for your application in terms of displaying the multivariate covariance function. Please try it out and let me know.

**Comment by lorebon** [comment] 2022-02-08 15:24
I installed the branch and I do not get any error. However, the resulting plot seems unsatisfactory:

![cov](https://user-images.githubusercontent.com/95094358/153018360-2931bd8a-da05-4b52-9ce1-6bcc6492079a.png)

Can you say if it's a problem of my dataset or something else?

**Comment by astamm** [comment] 2022-02-08 17:22
If your multivariate data set is of dimension 7, this does the right thing. We might improve the visual though by using the same color scale and displaying it just once. Would that be better for you?
Also it depends on the purpose of your visualization, but we could also display a single covariance structure out of the 28 available and let the user interactively select the one (s)he wants to see.

**Comment by lorebon** [comment] 2022-02-08 17:26
I think it can be a lot better simplying a single covariance structure just once, if it is not hard to implement.

**Comment by astamm** [comment] 2022-02-08 17:30
You mean choosing one of the 28 covariances only? Which one then? And why? What is the purpose here of what you are trying to achieve?

**Comment by lorebon** [comment] 2022-02-08 18:07
> You mean choosing one of the 28 covariances only? Which one then? And why? What is the purpose here of what you are trying to achieve?

I am interested in computing pairwise covariances among my 7 features.

**Comment by astamm** [comment] 2022-02-08 18:33
I am not following. In your previous comment, you say to plot a single covariance structure once. And now you want the pairwise (which is what the `plot` method currently does. What do you want precisely?

**Comment by lorebon** [comment] 2022-02-08 19:06
> I am not following. In your previous comment, you say to plot a single covariance structure once. And now you want the pairwise (which is what the `plot` method currently does. What do you want precisely?

My bad, I didn't explain myself well. 
I am interested in visualizing the functional covariance pairwise, among 7 features, but I cannot interpret the results I get.
It is not clear how my 7 features are pairwise correlated. Those heatmaps are not clear to me, and I wish I could 'zoom' in each of those little matrices.

**Comment by astamm** [comment] 2022-02-08 19:16
I understand a little bit better, thanks. Couple of questions:

- would it help to have a common shared color scale?
- we could think of an interactive plot which zooms in when you click on a particular plot but interactivity does not play well with every kinds of support. It is good for exploring within RStudio or for writing `Rmarkdown` reports rendered in HTML but not in PDF or producing presentations through Markdown as well.

**Comment by lorebon** [comment] 2022-02-08 19:18
> I understand a little bit better, thanks. Couple of questions:
> 
> * would it help to have a common shared color scale?

I thinks yes, absolutely.

> * we could think of an interactive plot which zooms in when you click on a particular plot but interactivity does not play well with every kinds of support. It is good for exploring within RStudio or for writing `Rmarkdown` reports rendered in HTML but not in PDF or producing presentations through Markdown as well.

I am not interested in interactivity.

Thank you again!

**Comment by astamm** [comment] 2022-02-08 19:22
> I wish I could 'zoom' in each of those little matrices.

Okay but then how do you wish to do this?

**Comment by lorebon** [comment] 2022-02-08 19:23
> > I wish I could 'zoom' in each of those little matrices.
> 
> Okay but then how do you wish to do this?

I'm thinking of creating bi-variate mfData and perform a loop over the plot function.

**Comment by astamm** [comment] 2022-02-08 19:25
Would that fit your needs if I add an optional parameter `choices` which would be a vector of indices which tells the `plot` method which subsets of features you want to display?

**Comment by lorebon** [comment] 2022-02-08 19:27
> Would that fit your needs if I add an optional parameter `choices` which would be a vector of indices which tells the `plot` method which subsets of features you want to display?

It would do the job.

**Comment by astamm** [comment] 2022-02-08 19:53
I just pushed something that should help. There is now a common color scale. And you can subset the features you want to display using e.g. `choices = 1:7` or `choices = 1:2` etc.

**Comment by lorebon** [comment] 2022-02-08 19:56
> I just pushed something that should help. There is now a common color scale. And you can subset the features you want to display using e.g. `choices = 1:7` or `choices = 1:2` etc.

OK, tomorrow I will test everything. Thank you!

**Comment by astamm** [comment] 2022-02-09 07:37
One thing that comes to my mind though. What is the point in visualising covariance instead of correlation? Aren'y you interested in pairwise correlations?

**Comment by lorebon** [comment] 2022-02-09 09:35
> One thing that comes to my mind though. What is the point in visualising covariance instead of correlation? Aren'y you interested in pairwise correlations?

I am interested in studying a form of dependence between those features. The only way I found is computing covariances thanks to this R package.

**Comment by astamm** [comment] 2022-02-09 10:22
So you want to see correlations I presume.

**Comment by astamm** [comment] 2022-02-09 10:23
But you do have multivariate functional data, right? What are these 7 features? a function that evaluates in R^7?

**Comment by lorebon** [comment] 2022-02-09 10:25
> But you do have multivariate functional data, right? What are these 7 features? a function that evaluates in R^7?

Those 7 features are signals of physical quantities such as temperature and pressure, extracted from some sensors.

**Comment by lorebon** [comment] 2022-02-09 12:34
> I just pushed something that should help. There is now a common color scale. And you can subset the features you want to display using e.g. `choices = 1:7` or `choices = 1:2` etc.

I installed the new branch and this is what I've got:

![conFunAfterFix](https://user-images.githubusercontent.com/95094358/153201739-45f4c9ab-c209-4d7d-b0ad-7b39aac515bd.png)

Surely it is a much better visualization, but still I can't interpret the result: what do represent those coloured sub-matrices in those specific positions?

**Comment by astamm** [comment] 2022-02-09 12:44
This is exactly why I asked about correlations VS covariances and what were your *features*. Putting everything on the same covariance scale does not make any sense here. We should rather always display correlations I guess.
Anyway, as for the interpretation, diagonal covariance matrices are regular covariances for each feature and off-diagonal ones, say `(1, 2)`, is covariance between feature 1 and feature 2.

**Comment by astamm** [comment] 2022-02-09 12:45
The whole thing assumes each feature has been observed on the same time grid.

**Comment by lorebon** [comment] 2022-02-09 12:58
> This is exactly why I asked about correlations VS covariances and what were your _features_. Putting everything on the same covariance scale does not make any sense here. We should rather always display correlations I guess.

OK now I understand, is it possible to diplay correlations?

> Anyway, as for the interpretation, diagonal covariance matrices are regular covariances for each feature and off-diagonal ones, say `(1, 2)`, is covariance between feature 1 and feature 2.

I know this, I was asking about the inner matrices inside them. For example, in (1,2) seems that there is a little block matrix.

**Comment by astamm** [comment] 2022-02-09 13:10
> OK now I understand, is it possible to diplay correlations?

Yes I will modify this and let you know.

**Comment by astamm** [comment] 2022-02-09 20:38
You can test from my usual branch now. You must now call the function `corrr::correlate()` on an `fData` or `mfData` object and then plot it via `ggplot2::autoplot()`.

**Comment by astamm** [comment] 2022-02-09 20:42
I made an additional commit so you can call the regular `plot()` function on the output of `corrr::correlate()`.

**Comment by lorebon** [comment] 2022-02-10 09:46
> You can test from my usual branch now. You must now call the function `corrr::correlate()` on an `fData` or `mfData` object and then plot it via `ggplot2::autoplot()`.

When I try to run the command `out = corrr::correlate(mfData)` I get the following error:

`Error in .x$values : $ operator is invalid for atomic vectors`

Am I missing something?

**Comment by astamm** [comment] 2022-02-10 10:09
Hard to tell. What is `mfData`? Can you provide the full reproducible example please?

**Comment by lorebon** [comment] 2022-02-10 10:21
OK, for some reason the way I install your latest branch doesn't work anymore: I get the old error of `cov_fun`.
Just for clarity, this is the way I try to install the 'ggplot2-conversion' branch:

`devtools::install_github("astamm/roahd", ref="ggplot2-conversion")`

It worked for a while, but now it doesn't. How can I fix this?

**Comment by astamm** [comment] 2022-02-10 10:24
I usually use the syntax `devtools::install_github("astamm/roahd@ggplot2-conversion")`.

**Comment by lorebon** [comment] 2022-02-10 12:39
OK, it seems that I'm stuck in some older version.
My installed one is the 1.4.3.9000, does it match yours?

**Comment by astamm** [comment] 2022-02-10 13:30
Yes. As asked before, you can provide a reproducible example I can run please?

**Comment by lorebon** [comment] 2022-02-10 15:13
> Yes. As asked before, you can provide a reproducible example I can run please?

From the documentation of mfData:

N = 1e2
P = 1e3
t0 = 0
t1 = 1
grid = seq( t0, t1, length.out = P )
C = exp_cov_function( grid, alpha = 0.3, beta = 0.4 )
Data_1 = generate_gauss_fdata( N, centerline = sin( 2 * pi * grid ), Cov = C )
Data_2 = generate_gauss_fdata( N, centerline = sin( 2 * pi * grid ), Cov = C )
multiData = mfData( grid, list( Data_1, Data_2 ) )

I tried with this `multiData` object.

**Comment by astamm** [comment] 2022-02-10 16:10
I cannot reproduce your problem. It works fine when I run your code. Although a bit slow, given the size of `P` which you might consider lowering down to, say, `100L`.

**Comment by astamm** [comment] 2022-02-10 16:15
![image](https://user-images.githubusercontent.com/6044838/153449166-d392eb0b-a042-4f38-933c-f669bec33474.png)

This is my result which is in accordance with the code I wrote up.

**Comment by astamm** [comment] 2022-02-10 16:18
Here is the same simulation with `beta = 4` so that correlation between time points is decreased a bit to better get the idea of what the `plot` method does:
![image](https://user-images.githubusercontent.com/6044838/153449834-ab079bff-469d-4df7-8b4e-8757d83bf3d8.png)

**Comment by lorebon** [comment] 2022-02-10 16:52
With my reproducible example, I get the same results and it is OK.
But the starting problem on plot(cov.fun) came back!

**Comment by astamm** [comment] 2022-02-10 17:56
My bad, I might have explained myself not well. You should plot correlations. To do that from an `fData` or an `mfData` object, you should first convert it into a proper correlation via `corrr::correlate()` and then you can plot the resulting object using either `ggplot2::autoplot()` or `plot()`.

I will make it clearer with proper documentation once we tailor the plot that best fits most user cases.

**Comment by lorebon** [comment] 2022-02-11 10:52
OK, now I understand. 
For some reason, my personal mfData is not working unlike the above example.
I am trying to debug, this is the traceback() result:

6: cbind(.x$values, .y$values)
5: fn(out, elt, ...)
4: reduce_impl(.x, .f, ..., .init = .init, .dir = .dir)
3: purrr::reduce(x$fDList, ~cbind(.x$values, .y$values))
2: correlate.mfData(multiData, use = "pairwise.complete.obs", method = "pearson")
1: corrr::correlate(multiData, use = "pairwise.complete.obs", method = "pearson")

It seems that it cannot access to values of the .x object. I will further investigate

**Comment by astamm** [comment] 2022-03-01 10:04
@LorenzoBonasera any updates on this?

**Comment by lorebon** [comment] 2022-03-01 10:23
> @LorenzoBonasera any updates on this?

Sorry for the late response, but I left this part of the project. Thank you!

**Comment by astamm** [comment] 2022-03-01 10:27
Thanks for getting back at me but that leaves it in a very unsatisfactory state from my standpoint. I did spend some time trying to fit your needs. It could be nice to give me some feedback so I can be sure that it is working properly or implement fixes in case it does not.

**Comment by lorebon** [comment] 2022-03-01 10:40
> Thanks for getting back at me but that leaves it in a very unsatisfactory state from my standpoint. I did spend some time trying to fit your needs. It could be nice to give me some feedback so I can be sure that it is working properly or implement fixes in case it does not.

OK. I tried to further debug but I cannot get where the error lies. The trackeback is reported above. 
The problem is that I cannot provide you my data since they are private. 
With synthetic data it seems to work, so I don't know what to do.

**Comment by astamm** [comment] 2022-03-01 10:47
How is your `mfData$fDList` list structured? Does each element of that list has a `"values"` entry? Are these entries all matrices with same number of rows (sample size)?

**Comment by lorebon** [comment] 2022-03-01 10:52
Here is a picture of my private raw mfData:

![raw_debug](https://user-images.githubusercontent.com/95094358/156156016-00cf3f2d-f336-4267-ac0d-0f347a8ff5b3.PNG)

**Comment by lorebon** [comment] 2022-03-01 10:52
Whereas this is the picture of synthetic data:

![synthetic_debug](https://user-images.githubusercontent.com/95094358/156156127-03e04feb-1cb9-44e9-a8be-800262375dc1.PNG)

**Comment by astamm** [comment] 2022-03-01 10:58
In `multiData$fDlist`, there are 7 elements. What's the size of the `values` matrix for each entry?

**Comment by lorebon** [comment] 2022-03-01 11:00
> In `multiData$fDlist`, there are 7 elements. What's the size of the `values` matrix for each entry?

Each 'values' matrix is 1068 x 1474

**Comment by astamm** [comment] 2022-03-01 11:05
Ok. Do you mind trying again the following:

- install the `corrr` package from CRAN;
- install the dev version of `roahd` via `devtools::install_github("astamm/roahd@ggplot2-conversion")`;
- run `corrr::correlate(multiData)`.

**Comment by lorebon** [comment] 2022-03-01 11:45
OK. Now I get different errors.
This is what I get when I run `corrr::correlate(multiData)`:

>Correlation method: 'pearson'
>Missing treated using: 'pairwise.complete.obs'
>Warning message:
>In stats::cor(x = x, y = y, use = use, method = method) :
>standard deviation is zero

**Comment by astamm** [comment] 2022-03-01 11:49
So that explicitly says you have variables with zero variance.
If you remove them, that should work.

**Comment by lorebon** [comment] 2022-03-01 11:50
OK, but it's a warning and it does not stop the code. When I try to run `plot`, I get lots of the following line:

> Don't know how to automatically pick scale for object of type noquote. Defaulting to continuous.

**Comment by astamm** [comment] 2022-03-01 13:33
Ok I reported that to the maintainers of the `corrr` package.
Does the `roahd` code now does what you wanted?

**Comment by lorebon** [comment] 2022-03-02 14:31
I removed the zero-variance variables, now I don't get that warning anymore.
The `corrr::correlate(multiData)` command runs properly, but when I call the `plot` function I get this:
![debug](https://user-images.githubusercontent.com/95094358/156381440-a1e9db29-e6f7-4b40-b920-a144008ab1af.PNG)

and it takes a very long time to end, without plotting anything.

**Comment by astamm** [comment] 2022-03-02 14:41
This message will be fixed soon either by `corrr` developers or `ggplot2` developers. I filed an issue and we are discussing the best way to address this.
Now, back to your data, you should see this message exactly 28 times because your dimension is 7.
I count 15 occurrences which is odd.
Then you should see a plot...
What does `autoplot()` output?

**Comment by lorebon** [comment] 2022-03-02 15:19
> Now, back to your data, you should see this message exactly 28 times because your dimension is 7. I count 15 occurrences > > which is odd. 

I cut two features that had zero variance in some rare cases. So from now there are only five features.

> Then you should see a plot... 

There is no plot after those messages.

> What does `autoplot()` output?

Same behaviour: 15 messages and no plot.

**Comment by astamm** [comment] 2022-03-02 15:31
I suspect a memory issue here. I see your first dimension has 1474 variables. If all 5 dimensions have similar numbers, then you are basically asking to display a `7500x7500` correlation matrix, which requires a huge amount of memory and quite some time to generate the image.
To test my hypothesis, try sampling some variables, say 10, per dimension and see if the plot does show up.

**Comment by lorebon** [comment] 2022-03-02 15:47
OK, I made the same hypothesis and I think we are right. Taking a sample of 100 per dimension, I get the following plot:
![debug](https://user-images.githubusercontent.com/95094358/156396123-7474f09b-6f81-4d24-9591-1f4ade59f3da.png)

I think that now it works, but the plot has no meaning since I am random sampling from time series data, in which the order is extremely important. This is something only related to my data, so I am sure that now the package works fine.

**Comment by astamm** [comment] 2022-03-02 15:50
you can take the same sample of 100 across dimensions if we want to be sure of the meaning of this. Otherwise, I am glad it is resolved.

**Comment by lorebon** [comment] 2022-03-02 15:52
> you can take the same sample of 100 across dimensions if we want to be sure of the meaning of this. Otherwise, I am glad it is resolved.

I used the command `df = sample_n(df, 100)`, that I think works across dimensions. The issue is that it is a very heavy downsampling, so features lose their meaning. I can try with other numbers. Thank you for all your efforts!

**Comment by astamm** [comment] 2022-03-02 16:11
You're welcome! Thanks for sticking with me to add this nice feature.

**Closed as completed by astamm** 2022-03-02 16:11 UTC
